language: python

python:
- "2.7"
- "3.4"

env:
- TOXENV=d16
- TOXENV=d17
- TOXENV=cov

install: pip install --quiet --use-mirrors tox

script: tox

after_script:
- if [ $TOXENV == "cov" ]; then
    pip install --quiet --use-mirrors coveralls;
    coveralls;
  fi