language: python

python:
- "2.7"

env:
- TOXENV=py27-d16
- TOXENV=py27-d17
- TOXENV=py34-d17
- TOXENV=cov

branches:
    only:
    - master
    - develop

install: pip install --quiet tox

script: tox

after_script:
- if [ $TOXENV == "cov" ]; then
    pip install --quiet coveralls;
    coveralls;
  fi
